# Setting Up Necessary Things

In [1]:
%reload_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
import torch
import numpy as np
import pandas as pd
from torch import tensor

In [3]:
# from google.colab import drive
# drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# %cd /content/drive/MyDrive/MasterCourse/Week 11 - Building Neural Networks with PyTorch/Lecture 41 - Build A Linear Model

/content/drive/MyDrive/MasterCourse/Week 11 - Building Neural Networks with PyTorch/Lecture 41 - Build A Linear Model


# Get Data

In [11]:
!gdown 1a4TCpVXvqyVhIGfULqCOg4COejFtcZrk
!gdown 1q_WCC0aLa0Xyyz6Um2_y2BDW6rjEfaHE

Downloading...
From: https://drive.google.com/uc?id=1a4TCpVXvqyVhIGfULqCOg4COejFtcZrk
To: /content/adult_train.csv
100% 4.60M/4.60M [00:00<00:00, 212MB/s]
Downloading...
From: https://drive.google.com/uc?id=1q_WCC0aLa0Xyyz6Um2_y2BDW6rjEfaHE
To: /content/adult_test.csv
100% 1.15M/1.15M [00:00<00:00, 164MB/s]


The reason we converted categorical values into numbers because computer do not understand text.

In [12]:
train_df = pd.read_csv("adult_train.csv")
test_df = pd.read_csv("adult_test.csv")
train_df.head()

age  fnlwgt  educational-num  hours-per-week  log-capital-gain  \
0   71   77253                9              17               0.0   
1   17  329783                6              10               0.0   
2   27   91257                9              40               0.0   
3   43  125577                9              40               0.0   
4   31  137978               13              40               0.0   

   log-capital-loss  private_workclass  postgrad_education  \
0               0.0               True                   0   
1               0.0               True                   0   
2               0.0               True                   0   
3               0.0               True                   0   
4               0.0               True                   0   

   after_HS_education  school_education  ...  relationship_Husband  \
0                   1                 0  ...                 False   
1                   0                 1  ...                 False   
2                   1                 0  ...                  True   
3                   1                 0  ...                 False   
4                   1                 0  ...                  True   

   relationship_Not-in-family  relationship_Other-relative  \
0                        True                        False   
1                       False                         True   
2                       False                        False   
3                       False                        False   
4                       False                        False   

   relationship_Own-child  relationship_Unmarried  relationship_Wife  \
0                   False                   False              False   
1                   False                   False              False   
2                   False                   False              False   
3                   False                    True              False   
4                   False                   False              False   

   race_white  gender_male  country_US  high_income  
0        True         True        True        False  
1        True        False        True        False  
2        True         True       False        False  
3       False        False        True        False  
4        True         True        True        False  

[5 rows x 25 columns]

In [13]:
train_df.shape, test_df.shape

((39073, 25), (9769, 25))

In [14]:
train_df.columns

Index(['age', 'fnlwgt', 'educational-num', 'hours-per-week',
       'log-capital-gain', 'log-capital-loss', 'private_workclass',
       'postgrad_education', 'after_HS_education', 'school_education',
       'married', 'occupation_cat_blue_collar', 'occupation_cat_others',
       'occupation_cat_service', 'occupation_cat_white_collar',
       'relationship_Husband', 'relationship_Not-in-family',
       'relationship_Other-relative', 'relationship_Own-child',
       'relationship_Unmarried', 'relationship_Wife', 'race_white',
       'gender_male', 'country_US', 'high_income'],
      dtype='object')

In [15]:
labels = tensor(train_df.high_income, dtype=torch.int)
labels[:5]

tensor([0, 0, 0, 0, 0], dtype=torch.int32)

In [16]:
feature_df = train_df[train_df.columns[:-1]].astype(float)
features = tensor(feature_df.values, dtype=torch.float)
features[:5]

tensor([[7.1000e+01, 7.7253e+04, 9.0000e+00, 1.7000e+01, 0.0000e+00, 0.0000e+00,
         1.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00, 0.0000e+00, 1.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00],
        [1.7000e+01, 3.2978e+05, 6.0000e+00, 1.0000e+01, 0.0000e+00, 0.0000e+00,
         1.0000e+00, 0.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00, 0.0000e+00, 1.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00, 1.0000e+00],
        [2.7000e+01, 9.1257e+04, 9.0000e+00, 4.0000e+01, 0.0000e+00, 0.0000e+00,
         1.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00,
         0.0000e+00, 1.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 1.0000e+00, 1.0000e+00, 0.0000e+00],
        [4.3000e+01, 1.25

In [17]:
features.shape, labels.shape

(torch.Size([39073, 24]), torch.Size([39073]))

# One Step of Linear Model

1. Initialize weights randomly and normalize data
2. Calculate Prediction (weights * features) { $h(x) = W * x$ }
3. Calculate Loss
4. Backpropagation
5. Gradient Step $W = W - lr * grad$

### Initialize weights randomly

In [18]:
torch.manual_seed(42)
n_params = features.shape[1]           #for 24 features, 24 weights will create
weights = torch.rand(n_params)         #24 weights created
weights

tensor([0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566, 0.7936, 0.9408,
        0.1332, 0.9346, 0.5936, 0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739,
        0.2666, 0.6274, 0.2696, 0.4414, 0.2969, 0.8317])

In [19]:
weights.shape

torch.Size([24])

### Normalization

* computes the maximum value for each column (feature) in the features tensor. here 0 denotes columns wise iteration.
* _ : The indices of the max values (not used in this case).

In [22]:
max_value, _ = features.max(dim=0)
features /= max_value
features

tensor([[0.7889, 0.0520, 0.5625,  ..., 1.0000, 1.0000, 1.0000],
        [0.1889, 0.2221, 0.3750,  ..., 1.0000, 0.0000, 1.0000],
        [0.3000, 0.0615, 0.5625,  ..., 1.0000, 1.0000, 0.0000],
        ...,
        [0.4000, 0.0920, 0.6250,  ..., 1.0000, 1.0000, 1.0000],
        [0.3556, 0.0539, 0.5625,  ..., 1.0000, 1.0000, 1.0000],
        [0.3333, 0.1355, 0.4375,  ..., 0.0000, 0.0000, 1.0000]])

### Calculate Prediction

In [51]:
def calculate_preds(weights, features):
  mults = (features * weights)
  preds = mults.sum(axis=1)
  return preds

In [52]:
preds = calculate_preds(weights, features)
preds[:5]

tensor([-0.8572, -0.5513, -0.6969,  0.0781, -1.2773], grad_fn=<SliceBackward0>)

### Calculate Loss

In [54]:
def calculate_loss(preds, labels):
  return torch.abs(preds-labels).mean()

In [55]:
loss = calculate_loss(preds, labels)
loss

tensor(0.8444, grad_fn=<MeanBackward0>)

### Calculate Gradients and Backpropagation

In [27]:
#is used in PyTorch to enable gradient tracking for the weights tensor.
#It modifies weights in-place to require gradients for autograd (automatic differentiation).

weights.requires_grad_()

tensor([0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566, 0.7936, 0.9408,
        0.1332, 0.9346, 0.5936, 0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739,
        0.2666, 0.6274, 0.2696, 0.4414, 0.2969, 0.8317], requires_grad=True)

In [28]:
preds = calculate_preds(weights, features)
loss = calculate_loss(preds, labels)
loss

tensor(4.9282, grad_fn=<MeanBackward0>)

In [29]:
# Backpropagation
loss.backward()

In [30]:
weights.grad       #differentiation

tensor([0.4300, 0.1277, 0.6300, 0.4087, 0.0626, 0.0430, 0.6937, 0.0672, 0.8016,
        0.1312, 0.4703, 0.3276, 0.0575, 0.1059, 0.5090, 0.4026, 0.2586, 0.0314,
        0.1549, 0.1052, 0.0473, 0.8561, 0.6690, 0.8983])

### Gradient Step

In [56]:
learning_rate = 0.1

with torch.no_grad():
  weights.sub_(weights.grad * learning_rate)      #weight = weight - lr*grad. this is updated weight
  preds = calculate_preds(weights, features)
  loss = calculate_loss(preds, labels)
  print(loss)

tensor(7.1045)


# Setting Up everything together

In [57]:
train_feature_df = train_df[train_df.columns[:-1]].astype(float)
train_features = tensor(train_feature_df.values, dtype=torch.float)
train_labels = tensor(train_df.high_income, dtype=torch.int)

In [58]:
max_value, _ = train_features.max(dim=0)
train_features /= max_value

In [59]:
test_feature_df = test_df[test_df.columns[:-1]].astype(float)
test_features = tensor(test_feature_df.values, dtype=torch.float)
test_labels = tensor(test_df.high_income, dtype=torch.int)

In [60]:
max_value, _ = test_features.max(dim=0)
test_features /= max_value

In [36]:
def init_weights():
  torch.manual_seed(42)
  n_params = train_features.shape[1]
  weights = torch.rand(n_params)
  return weights.requires_grad_()

In [37]:
def calculate_preds(weights, features):
  mults = (features * weights)
  preds = mults.sum(axis=1)
  return preds

In [38]:
def calculate_loss(preds, labels):
  return torch.abs(preds-labels).mean()

In [39]:
def update_weights(weights, lr):
  weights.sub_(weights.grad * lr)
  return

In [40]:
def one_epoch(epoch_no, weights, lr):
  preds = calculate_preds(weights, features)
  loss = calculate_loss(preds, train_labels)
  loss.backward()
  with torch.no_grad(): update_weights(weights, lr)
  print(f"Epoch {epoch_no+1} => Loss: {loss}")

In [41]:
def train_model(epochs, lr):
  weights = init_weights()
  for epoch_no in range(epochs):
    one_epoch(epoch_no, weights, lr)
  return weights

In [42]:
weights = train_model(epochs=15, lr=0.01)

Epoch 1 => Loss: 4.928189754486084
Epoch 2 => Loss: 4.880458354949951
Epoch 3 => Loss: 4.7849955558776855
Epoch 4 => Loss: 4.641801834106445
Epoch 5 => Loss: 4.450876712799072
Epoch 6 => Loss: 4.212220668792725
Epoch 7 => Loss: 3.9258322715759277
Epoch 8 => Loss: 3.5917136669158936
Epoch 9 => Loss: 3.2098629474639893
Epoch 10 => Loss: 2.7802815437316895
Epoch 11 => Loss: 2.3029685020446777
Epoch 12 => Loss: 1.7779242992401123
Epoch 13 => Loss: 1.2055810689926147
Epoch 14 => Loss: 0.6818041205406189
Epoch 15 => Loss: 0.5160887837409973


In [43]:
weights       #updated weights

tensor([ 0.3738,  0.7640, -0.3614,  0.4764,  0.3168,  0.5498, -0.5607,  0.7137,
        -0.0060, -0.0221,  0.3816,  0.2074,  0.8004,  0.4415,  0.1404, -0.0430,
         0.5772,  0.5365,  0.0847,  0.5016,  0.2134, -0.5687, -0.4899, -0.2296],
       requires_grad=True)

### Saving model weights for future inference

In [44]:
torch.save(weights, "linear_model_weights.pt")

### Test Accuracy

In [45]:
test_preds = calculate_preds(weights, test_features)
test_preds[:5]

tensor([ 0.5129, -0.4021, -0.5087, -0.8819, -0.4508], grad_fn=<SliceBackward0>)

In [46]:
results = test_labels == (test_preds > 0.5).int()
results[:5]

tensor([False,  True,  True,  True, False])

In [47]:
results.float().mean()

tensor(0.7264)

**Together all**

In [48]:
def accuracy(weights, features):
  preds = calculate_preds(weights, features)
  results = test_labels == (preds > 0.5).int()
  return results.float().mean()

In [49]:
trained_weights = torch.load("linear_model_weights.pt")

<ipython-input-49-a42be6bd993c>:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  trained_weights = torch.load("linear_model_weights.pt")


In [50]:
accuracy(trained_weights, test_features)

tensor(0.7264)

*Our linear model's accuracy* **72.64%**